"""store complaint attachments in database

Revision ID: 5d606ef463d7
Revises: 0e265036f58b
Create Date: 2026-04-13 17:47:06.905774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d606ef463d7'
down_revision: Union[str, Sequence[str], None] = '0e265036f58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "complaint_attachments",
        sa.Column("file_size", sa.Integer(), nullable=True),
    )
    op.add_column(
        "complaint_attachments",
        sa.Column("file_content", sa.LargeBinary(), nullable=True),
    )

    op.drop_column("complaint_attachments", "file_path")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_attachments', sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('complaint_attachments', 'file_content')
    op.drop_column('complaint_attachments', 'file_size')
    # ### end Alembic commands ###
