"""add faq category label

Revision ID: b4159cd9bfd1
Revises: 527875d6834e
Create Date: 2026-04-07 18:41:34.534375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4159cd9bfd1'
down_revision: Union[str, Sequence[str], None] = '527875d6834e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
        # 1. додаємо колонку
        op.add_column(
            'faq_entries',
            sa.Column('category_label', sa.String(length=255), nullable=True)
        )

        # 2. заповнюємо значення
        op.execute("""
            UPDATE faq_entries
            SET category_label = category
        """)

        # 3. робимо NOT NULL
        op.alter_column(
            'faq_entries',
            'category_label',
            nullable=False
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faq_entries', 'category_label')
    # ### end Alembic commands ###
